name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write SSH key and test connection
        shell: bash
        run: |
          set -euxo pipefail
          # 1) пишемо ключ у файл, прибираючи CRLF якщо випадково є
          printf '%s\n' "${{ secrets.SSH_KEY }}" | sed 's/\r$//' > key.pem
          chmod 600 key.pem

          # 2) пробний конект
          ssh -vvv -o StrictHostKeyChecking=no -i key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'echo OK && uname -a && whoami'

      - name: Run deploy script
        if: ${{ success() }}
        shell: bash
        run: |
          set -euxo pipefail
          ssh -o StrictHostKeyChecking=no -i key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '/opt/flaskapp/scripts/deploy.sh'
